apiVersion: v1
kind: ConfigMap
metadata:
  name: ranger-admin-config
  labels:
    {{- include "ranger-admin.labels" . | nindent 4 }}
data:
  install.properties: |
    # Licensed to the Apache Software Foundation (ASF) under one or more
    # contributor license agreements.  See the NOTICE file distributed with
    # this work for additional information regarding copyright ownership.
    # The ASF licenses this file to You under the Apache License, Version 2.0
    # (the "License"); you may not use this file except in compliance with
    # the License.  You may obtain a copy of the License at
    #
    #     http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.

    #
    # This file provides a list of the deployment variables for the Policy Manager Web Application
    #

    PYTHON_COMMAND_INVOKER=python3
    RANGER_ADMIN_LOG_DIR=/var/log/ranger
    RANGER_PID_DIR_PATH=/var/run/ranger
    DB_FLAVOR=MYSQL
    SQL_CONNECTOR_JAR=/usr/share/java/mysql-connector.jar
    RANGER_ADMIN_LOGBACK_CONF_FILE=/opt/ranger/admin/ews/webapp/WEB-INF/classes/conf/logback.xml

    db_root_user=${env:DB_ROOT_USER:-""}
    db_root_password=${env:DB_ROOT_PASSWORD:-""}
    db_host=${env:DB_HOST:-""}

    db_name=${env:RANGER_DB_NAME:-ranger}
    db_user=${env:RANGER_DB_USER:-""}
    db_password=${env:RANGER_DB_PASSWORD:-""}

    postgres_core_file=db/postgres/optimized/current/ranger_core_db_postgres.sql
    postgres_audit_file=db/postgres/xa_audit_db_postgres.sql
    mysql_core_file=db/mysql/optimized/current/ranger_core_db_mysql.sql
    mysql_audit_file=db/mysql/xa_audit_db.sql

    rangerAdmin_password=${env:RANGER_ADMIN_PASSWORD:-"rangerR0cks!"}
    rangerTagsync_password=${env:RANGER_TAG_SYNC_PASSWORD:-"rangerR0cks!"}
    rangerUsersync_password=${env:RANGER_USER_SYNC_PASSWORD:-"rangerR0cks!"}
    keyadmin_password=${env:RANGER_KEY_ADMIN_PASSWORD:-"rangerR0cks!"}


    audit_store=solr
    audit_solr_urls=http://ranger-solr:8983/solr/ranger_audits
    audit_solr_collection_name=ranger_audits

    policymgr_external_url=http://{{ include "ranger-admin.fullname" . }}:6080
    policymgr_http_enabled=true

    unix_user=ranger
    unix_user_pwd=ranger
    unix_group=ranger

    # Following variables are referenced in db_setup.py. Do not remove these
    oracle_core_file=
    sqlserver_core_file=
    sqlanywhere_core_file=
    cred_keystore_filename=

    # #################  DO NOT MODIFY ANY VARIABLES BELOW #########################
    #
    # --- These deployment variables are not to be modified unless you understand the full impact of the changes
    #
    ################################################################################
    XAPOLICYMGR_DIR=$PWD
    app_home=$PWD/ews/webapp
    TMPFILE=$PWD/.fi_tmp
    LOGFILE=$PWD/logfile
    LOGFILES="$LOGFILE"

    JAVA_BIN='java'
    JAVA_VERSION_REQUIRED='1.8'

    ranger_admin_max_heap_size=1g
    #retry DB and Java patches after the given time in seconds.
    PATCH_RETRY_INTERVAL=120
    STALE_PATCH_ENTRY_HOLD_TIME=10

    hadoop_conf=
    authentication_method=UNIX