apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ranger-admin.fullname" . }}
  labels:
    {{- include "ranger-admin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ranger-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ranger-admin.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ranger-admin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/bash", "-c" ]
          args:
            - "cp /opt/config-map/install.properties /opt/ranger/admin/ && chmod 777 /opt/ranger/admin/install.properties && /opt/ranger/replace_env_vars.sh /opt/ranger/admin/install.properties && /home/ranger/scripts/ranger.sh"
          env:
            - name: DB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: DB_ROOT_USER
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: DB_ROOT_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: DB_HOST
            - name: RANGER_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: RANGER_DB_NAME
            - name: RANGER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: RANGER_DB_USER
            - name: RANGER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: RANGER_DB_PASSWORD
            - name: RANGER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: RANGER_ADMIN_PASSWORD
            - name: RANGER_TAG_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: RANGER_TAG_SYNC_PASSWORD
            - name: RANGER_USER_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: RANGER_USER_SYNC_PASSWORD
            - name: RANGER_KEY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: RANGER_KEY_ADMIN_PASSWORD
            - name: POLICY_MANAGER_URL
              value: http://{{ include "ranger-admin.fullname" . }}:6080
            - name: ADMIN_USERNAME
              value: admin
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.data_plane_secret_name | default "data-plane-secrets" }}
                  key: RANGER_ADMIN_PASSWORD
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
