apiVersion: v2
name: trino-community
description: A Helm chart to manage Dview Trino Community dependencies
version: 0.1.0
dependencies:
  - name: openldap-stack-ha
    version: 4.1.2
    condition: openldap.enabled
  - name: ranger-admin
    version: 0.1.0
    condition: ranger-admin.enabled
  - name: ranger-usersync
    version: 0.1.0
    condition: ranger-usersync.enabled
  - name: trino
    version: 0.14.0
    condition: trino.enabled